[project]
name = "release"
version = "0.1.4"
description = "Release control process"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [ "semver>=3.0.4", "toml>=0.10.2",]
[[project.authors]]
name = "Steve Holden"
email = "steve@holdenweb.com"

[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project.scripts]
release = "release:main"
