#!/bin/bash

function project {
    uv version | awk '{print $1}'
}
trap "cd $save_dir; rm -rf $tmp_dir" EXIT

echo uv project is $(project)
# set up a temp working directory and a trap to remove it when exiting
save_dir=$(pwd)
tmp_dir=$(mktemp -d)
proj_name=$(basename $tmp_dir)
cd $tmp_dir
echo temp project is $proj_name
uv init                                     # Create a new project
